# Generated by Django 5.0.7 on 2024-07-10 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vige", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ricepe",
            new_name="Recipe",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="ricepe_description",
            new_name="recipe_description",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="ricepe_image",
            new_name="recipe_image",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="ricepe_name",
            new_name="recipe_name",
        ),
    ]
