# Generated by Django 5.0.7 on 2024-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vige", "0004_rename_recipe_description_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(default="Default Instructions"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
