# Generated by Django 5.0.7 on 2024-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vige", "0005_alter_recipe_instructions_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
