# Generated by Django 5.0.6 on 2024-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    # depend this migrationfile to other
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.TextField()),
                ("address", models.TextField()),
            ],
        ),
    ]
